# Generated by Django 4.1.7 on 2023-03-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=100)),
                ('Phone', models.IntegerField()),
                ('Game', models.CharField(max_length=100)),
                ('Date_Time', models.DateTimeField()),
            ],
        ),
    ]
