# Generated by Django 4.1.7 on 2023-07-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Isactive',
            field=models.BooleanField(default=False),
        ),
    ]
